apiVersion: batch/v2alphal
kind: CronJob
metadata:
  name: hello
spec:
  scheduler: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
          image: busybox
          command: ["echo", "hello k8s job!"]
      restartPolicy: OnFailure
