apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec: 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /nfsdata/pv1
    server: 192.168.0.2
